### PR TITLE
T16087 email templates

### PR DESCRIPTION
**Pull request by gctucker**
This is to fix and improve #135:
* add templates.yaml to define all the specific templates with their associated data
* remove hard-coded data from the code accordingly
* tweak arguments names and documentation to be more consistent
* still make use of the new API to be able to choose the template independently of the test plan
* look for a template with the same name as the test plan by default to keep current behaviour

### CODE REVIEW

**Comment by gctucker** [comment]
@touilkhouloud Please let me know if this works for you.  The idea is to squash the FIXUP commits and merge this PR instead of #135 as it fixes several issues as described above.

**Comment by touilkhouloud** [comment]
@gctucker yes sure.

**Comment by gctucker** [comment]
Tested OK on staging:
```
kernelci/staging.kernelci.org v4l2-compliance on uvcvideo: 4 runs, 0 regressions (staging-20190805.2)

Test results summary
--------------------

run | platform                 | arch   | lab                      | compiler | defconfig          | errors
----+--------------------------+--------+--------------------------+----------+--------------------+-------
  1 | rk3288-veyron-jaq        | arm    | lab-collabora-dev        | clang-8  | multi_v7_defconfig | 9/52
  2 | rk3288-veyron-jaq        | arm    | lab-collabora-dev        | gcc-8    | multi_v7_defconfig | 9/52
  3 | rk3399-gru-kevin         | arm64  | lab-collabora-dev        | clang-8  | defconfig          | 9/52
  4 | rk3399-gru-kevin         | arm64  | lab-collabora-dev        | gcc-8    | defconfig          | 9/52


V4L2 Compliance on the uvcvideo driver.

This test ran "v4l2-compliance -s" from v4l-utils:

    https://www.linuxtv.org/wiki/index.php/V4l2-utils

See each detailed section in the report below to find out the git URL and
particular revision that was used to build the test binaries.


  Tree:     kernelci
  Branch:   staging.kernelci.org
  Describe: staging-20190805.2
  URL:      https://github.com/kernelci/linux.git
  SHA:      6cb1dfff9766e5baf5d070302a29094daaf3a46e

  Test suite revisions:
    v4l2-compliance
      URL:  git://linuxtv.org/v4l-utils.git
      SHA:  6b63111c71eb2837195962d510c510b83c3821f0 


Test Failures
-------------
  

run | platform                 | arch   | lab                      | compiler | defconfig          | errors
----+--------------------------+--------+--------------------------+----------+--------------------+-------
  1 | rk3288-veyron-jaq        | arm    | lab-collabora-dev        | clang-8  | multi_v7_defconfig | 9/52

  Results:     43 PASS, 9 FAIL, 0 SKIP
  Full config: multi_v7_defconfig
  Compiler:    clang-8 (clang version 8.0.1-svn359952-1~exp1~20190504004501.65 (branches/release_80))
  Plain log:   http://staging-storage.kernelci.org/kernelci/staging.kernelci.org/staging-20190805.2/arm/multi_v7_defconfig/clang-8/lab-collabora-dev/v4l2-compliance-uvc-rk3288-veyron-jaq.txt
  HTML log:    http://staging-storage.kernelci.org/kernelci/staging.kernelci.org/staging-20190805.2/arm/multi_v7_defconfig/clang-8/lab-collabora-dev/v4l2-compliance-uvc-rk3288-veyron-jaq.html
  Rootfs:      http://storage.kernelci.org/images/rootfs/debian/stretch-v4l2/20190726.0/armhf/rootfs.cpio.gz             

  Control-ioctls-Input-0 - 6 tests: 4  PASS, 2 FAIL, 0 SKIP
    * VIDIOC_QUERY_EXT_CTRL/QUERYMENU: never passed
    * VIDIOC_G/S/TRY_EXT_CTRLS: never passed   

  Format-ioctls-Input-0 - 10 tests: 9  PASS, 1 FAIL, 0 SKIP
    * VIDIOC_G/S_PARM: never passed     

  Buffer-ioctls-Input-0 - 3 tests: 2  PASS, 1 FAIL, 0 SKIP
    * Requests: never passed   

  Streaming-ioctls_Test-input-0 - 7 tests: 2  PASS, 5 FAIL, 0 SKIP
    * MMAP-no-poll: never passed
    * MMAP-select: never passed
    * MMAP-epoll: never passed
    * USERPTR-no-poll: never passed
    * USERPTR-select: never passed  
      

run | platform                 | arch   | lab                      | compiler | defconfig          | errors
----+--------------------------+--------+--------------------------+----------+--------------------+-------
  2 | rk3288-veyron-jaq        | arm    | lab-collabora-dev        | gcc-8    | multi_v7_defconfig | 9/52

  Results:     43 PASS, 9 FAIL, 0 SKIP
  Full config: multi_v7_defconfig
  Compiler:    gcc-8 (arm-linux-gnueabihf-gcc (Debian 8.3.0-2) 8.3.0)
  Plain log:   http://staging-storage.kernelci.org/kernelci/staging.kernelci.org/staging-20190805.2/arm/multi_v7_defconfig/gcc-8/lab-collabora-dev/v4l2-compliance-uvc-rk3288-veyron-jaq.txt
  HTML log:    http://staging-storage.kernelci.org/kernelci/staging.kernelci.org/staging-20190805.2/arm/multi_v7_defconfig/gcc-8/lab-collabora-dev/v4l2-compliance-uvc-rk3288-veyron-jaq.html
  Rootfs:      http://storage.kernelci.org/images/rootfs/debian/stretch-v4l2/20190726.0/armhf/rootfs.cpio.gz             

  Control-ioctls-Input-0 - 6 tests: 4  PASS, 2 FAIL, 0 SKIP
    * VIDIOC_QUERY_EXT_CTRL/QUERYMENU: never passed
    * VIDIOC_G/S/TRY_EXT_CTRLS: never passed   

  Format-ioctls-Input-0 - 10 tests: 9  PASS, 1 FAIL, 0 SKIP
    * VIDIOC_G/S_PARM: never passed     

  Buffer-ioctls-Input-0 - 3 tests: 2  PASS, 1 FAIL, 0 SKIP
    * Requests: never passed   

  Streaming-ioctls_Test-input-0 - 7 tests: 2  PASS, 5 FAIL, 0 SKIP
    * MMAP-no-poll: never passed
    * MMAP-select: never passed
    * MMAP-epoll: never passed
    * USERPTR-no-poll: never passed
    * USERPTR-select: never passed  
      

run | platform                 | arch   | lab                      | compiler | defconfig          | errors
----+--------------------------+--------+--------------------------+----------+--------------------+-------
  3 | rk3399-gru-kevin         | arm64  | lab-collabora-dev        | clang-8  | defconfig          | 9/52

  Results:     43 PASS, 9 FAIL, 0 SKIP
  Full config: defconfig
  Compiler:    clang-8 (clang version 8.0.1-svn359952-1~exp1~20190504004501.65 (branches/release_80))
  Plain log:   http://staging-storage.kernelci.org/kernelci/staging.kernelci.org/staging-20190805.2/arm64/defconfig/clang-8/lab-collabora-dev/v4l2-compliance-uvc-rk3399-gru-kevin.txt
  HTML log:    http://staging-storage.kernelci.org/kernelci/staging.kernelci.org/staging-20190805.2/arm64/defconfig/clang-8/lab-collabora-dev/v4l2-compliance-uvc-rk3399-gru-kevin.html
  Rootfs:      http://storage.kernelci.org/images/rootfs/debian/stretch-v4l2/20190726.0/arm64/rootfs.cpio.gz             

  Control-ioctls-Input-0 - 6 tests: 4  PASS, 2 FAIL, 0 SKIP
    * VIDIOC_QUERY_EXT_CTRL/QUERYMENU: never passed
    * VIDIOC_G/S/TRY_EXT_CTRLS: never passed   

  Format-ioctls-Input-0 - 10 tests: 9  PASS, 1 FAIL, 0 SKIP
    * VIDIOC_G/S_PARM: never passed     

  Buffer-ioctls-Input-0 - 3 tests: 2  PASS, 1 FAIL, 0 SKIP
    * Requests: never passed   

  Streaming-ioctls_Test-input-0 - 7 tests: 2  PASS, 5 FAIL, 0 SKIP
    * MMAP-no-poll: never passed
    * MMAP-select: never passed
    * MMAP-epoll: never passed
    * USERPTR-no-poll: never passed
    * USERPTR-select: never passed  
      

run | platform                 | arch   | lab                      | compiler | defconfig          | errors
----+--------------------------+--------+--------------------------+----------+--------------------+-------
  4 | rk3399-gru-kevin         | arm64  | lab-collabora-dev        | gcc-8    | defconfig          | 9/52

  Results:     43 PASS, 9 FAIL, 0 SKIP
  Full config: defconfig
  Compiler:    gcc-8 (aarch64-linux-gnu-gcc (Debian 8.3.0-2) 8.3.0)
  Plain log:   http://staging-storage.kernelci.org/kernelci/staging.kernelci.org/staging-20190805.2/arm64/defconfig/gcc-8/lab-collabora-dev/v4l2-compliance-uvc-rk3399-gru-kevin.txt
  HTML log:    http://staging-storage.kernelci.org/kernelci/staging.kernelci.org/staging-20190805.2/arm64/defconfig/gcc-8/lab-collabora-dev/v4l2-compliance-uvc-rk3399-gru-kevin.html
  Rootfs:      http://storage.kernelci.org/images/rootfs/debian/stretch-v4l2/20190726.0/arm64/rootfs.cpio.gz             

  Control-ioctls-Input-0 - 6 tests: 4  PASS, 2 FAIL, 0 SKIP
    * VIDIOC_QUERY_EXT_CTRL/QUERYMENU: never passed
    * VIDIOC_G/S/TRY_EXT_CTRLS: never passed   

  Format-ioctls-Input-0 - 10 tests: 9  PASS, 1 FAIL, 0 SKIP
    * VIDIOC_G/S_PARM: never passed     

  Buffer-ioctls-Input-0 - 3 tests: 2  PASS, 1 FAIL, 0 SKIP
    * Requests: never passed   

  Streaming-ioctls_Test-input-0 - 7 tests: 2  PASS, 5 FAIL, 0 SKIP
    * MMAP-no-poll: never passed
    * MMAP-select: never passed
    * MMAP-epoll: never passed
    * USERPTR-no-poll: never passed
    * USERPTR-select: never passed  
```

**Comment by gctucker** [comment]
Thanks @touilkhouloud @khilman - I've now force-pushed with a cleaned-up patch series.  I'll get this tested again on staging tonight, let me know if you spot anything in this final version.

**Comment by gctucker** [comment]
Today's version worked as well on staging, all email reports look normal.

**Comment by touilkhouloud** [comment]
So now we can choose the template to be used regardless the test plan :)

**Comment by gctucker** [comment]
@touilkhouloud Yes, as long as it's listed in the YAML file.

**Comment by touilkhouloud** [comment]
@gctucker Thanks for your efforts and for your reviews :) .

**Comment by gctucker** [comment]
np :) I just need to fix a couple of unit tests now, will push an update.

**Pull request merged**
