### PR TITLE
T10505 test groups

### PR DESCRIPTION
**Pull request by gctucker**
Implement test groups with test results, and nested sub-groups:
* parse LAVA test callback data into test groups with test cases, and test sets as sub-groups
* recursively import into the database a structure with test groups containing sub-groups and cases
* generate test email reports (text and html) with one level of sub-groups
* updated documentation and database schema documents

### CODE REVIEW

**Comment by gctucker** [comment]
This replaces #75 which was removed by mistake.

Sample email test reports with modified "simple" test plan to include sets:
https://people.collabora.com/~gtucker/tmp/test-report-email-002.html
https://people.collabora.com/~gtucker/tmp/test-report-email-002.txt

**Comment by gctucker** [comment]
Note: Posting test results via the `test/` entry point is known to be broken, this PR has only been tested with the `callback/lava` entry points for labs that run LAVA.  The `test/` API issue may be fixed in a separate PR.

**Comment by khilman** [comment]
Looking at the sample email text, I have some questions:

```
simple - 7 tests: 6  PASS, 1 FAIL, 0 SKIP

  Config:      defconfig
  Lab Name:    gtucker-lava-testing
  Board:       qemu
  Date:        2018-09-11 13:52:00.296000

  Test cases:

    * whoami: PASS

  networking - 3 tests: 2  PASS, 1 FAIL, 0 SKIP

    * ping: FAIL
    * ip: PASS
    * udhcpc: PASS

  filesystem - 3 tests: 3  PASS, 0 FAIL, 0 SKIP

    * ls: PASS
    * mount: PASS
    * df: PASS
```
Is this already using groups?  This is kind of confusing, as the summary shows 7 test, but then below where it shows "Test cases" it shows 1 (whoami) followed by some groups.  How is it breaking those up into groups?

**Comment by gctucker** [comment]
@khilman This job has one test case that doesn't belong to any test suite, so it's in the top group.  I don't think we'll see many of these with real tests but I used it to test the code.  The hierarchy goes like this:

* **simple** (test plan)
  * whoami (test case)
  * **networking** (test group)
    * ping
    * ip
    * udhcpc
  * **filesystem** (test group)
    * ls
    * mount
    * df

The modified `simple` test template for this is basically:
```yaml
          steps:
          - lava-test-case whoami --shell whoami
          - lava-test-set start filesystem
          - lava-test-case df --shell df -h
          - lava-test-case mount --shell mount
          - lava-test-case ls --shell ls /
          - lava-test-set stop
          - lava-test-set start networking
          - lava-test-case udhcpc --shell udhcpc
          - lava-test-case ip --shell ip addr
          - lava-test-case ping --shell ping -c4 8.8.8.8
          - lava-test-set stop
```
The formatting of the email report can surely be improved, I haven't spent too much time on this aspect.  Does the data structure make more sense now?

**Comment by gctucker** [comment]
Also the summary line shows the total of all the cases in the test plan, across all its sub-groups.

**Comment by khilman** [comment]
OK, thanks for clarifying.  It makes sense now.

**Comment by gctucker** [comment]
Temporary html doc generated with this branch:
https://people.collabora.com/~gtucker/kernelci/doc/backend-doc-html-20180914/

Note the test group parts:
https://people.collabora.com/~gtucker/kernelci/doc/backend-doc-html-20180914/collection-test.html
https://people.collabora.com/~gtucker/kernelci/doc/backend-doc-html-20180914/schema-test.html
https://people.collabora.com/~gtucker/kernelci/doc/backend-doc-html-20180914/examples.html#uploading-tests

**Comment by khilman** [comment]
> Temporary html doc generated with this branch:
> [https://people.collabora.com/~gtucker/kernelci/doc/backend-doc-html-20180914/](https://people.collabora.com/%7Egtucker/kernelci/doc/backend-doc-html-20180914/)
> 
> Note the test group parts:
> [https://people.collabora.com/~gtucker/kernelci/doc/backend-doc-html-20180914/collection-test.html](https://people.collabora.com/%7Egtucker/kernelci/doc/backend-doc-html-20180914/collection-test.html)
> [https://people.collabora.com/~gtucker/kernelci/doc/backend-doc-html-20180914/schema-test.html](https://people.collabora.com/%7Egtucker/kernelci/doc/backend-doc-html-20180914/schema-test.html)
> [https://people.collabora.com/~gtucker/kernelci/doc/backend-doc-html-20180914/examples.html#uploading-tests](https://people.collabora.com/%7Egtucker/kernelci/doc/backend-doc-html-20180914/examples.html#uploading-tests)

Thanks for updating the docs also!  
I noticed that the "uploading tests" part is updated too.  Did you test that to see if it works?  My understanding was that using the /test API directly wasn't working well.  Or maybe you fixed it in the process of this cleanup?

**Comment by gctucker** [comment]
@khilman from the last commit:

> Note: The POST API to submit test results appears to not be functional
at the moment, so the documentation hasn't been updated with examples
to upload sub-groups this way.  Only LAVA callbacks can be used at the
moment to submit sub-groups via LAVA test sets.

So no, it probably doesn't work but it was trivial to update the docs to match the changes in the database models.  I have a task in my backlog to take a look and fix the `/tests/` API entry point as a follow up.  I think it would be really useful for people / companies with a non-LAVA lab who want to contribute to KernelCI.

**Pull request merged**
