### PR TITLE
T12987 Add compiler in bisection email reports

### PR DESCRIPTION
**Pull request by gctucker**
Add the compiler name and version if available in bisection email
reports.  This is especially useful now as we're starting to support
multiple compilers.

Signed-off-by: Guillaume Tucker <guillaume.tucker@collabora.com>

### CODE REVIEW

**Comment by gctucker** [comment]
Tested OK on staging, here's a sample report from a test bisection:
```
gtucker/kernelci-local boot bisection: kernelci-local-snapshot-029-9-gefba99b66b38 on beaglebone-black #7468-staging

Summary:
  Start:      efba99b66b38 NOISE Special cases aren't special enough...
  Details:    https://staging.kernelci.org/boot/id/5c640567cf3a0fb932ef2f91
  Plain log:  http://staging-storage.kernelci.org/gtucker/kernelci-local/kernelci-local-snapshot-029-9-gefba99b66b38/arm/multi_v7_defconfig/lab-collabora-dev/boot-am335x-boneblack.txt
  HTML log:   http://staging-storage.kernelci.org/gtucker/kernelci-local/kernelci-local-snapshot-029-9-gefba99b66b38/arm/multi_v7_defconfig/lab-collabora-dev/boot-am335x-boneblack.html
  Result:     95cf16291f27 BREAK panic on any device tree platform

Checks:
  revert:     PASS
  verify:     PASS

Parameters:
  Tree:       gtucker
  URL:        https://gitlab.collabora.com/gtucker/linux.git
  Branch:     kernelci-local
  Target:     beaglebone-black
  CPU arch:   arm
  Lab:        lab-collabora-dev
  Compiler:   gcc-7
  Config:     multi_v7_defconfig
  Test suite: boot
```

**Comment by gctucker** [comment]
Just realised that the boot links were broken just like in the test report emails, the build environment is missing from the path.

**Comment by mattface** [comment]
Dont these use the file_server_resource from the build metadata? I thought that was embedded into the boot/test job metadata as well?

**Comment by gctucker** [comment]
There's no meta-data for the builds made by the bisection job in the backend, but it's possible to make the bisection job send it as part of the bisection results meta-data.

**Comment by gctucker** [comment]
Tested again with extra fixes: https://github.com/kernelci/kernelci-core-staging/pull/96#issuecomment-463651700

**Pull request merged**
