### PR TITLE
Remove deprecated "low-level" test API

### PR DESCRIPTION
**Pull request by mgalka**
Remove handlers, tests and docs for test API calls, which are
not supposed to be used anymore.
These were the methods for manipulating single test_case and
single test_group documents.

### CODE REVIEW

**Comment by gctucker** [comment]
Looks good at first glance, testing this on staging today.

@mgalka Out of interest, how do you verify that the new POST API to send test results still works?  I guess there are unit tests, but how do you run end-to-end tests? (sorry if you already explained that in a previous PR...)

**Comment by mgalka** [comment]
> Looks good at first glance, testing this on staging today.
> 
> @mgalka Out of interest, how do you verify that the new POST API to send test results still works? I guess there are unit tests, but how do you run end-to-end tests? (sorry if you already explained that in a previous PR...)

It's been tested exactly the same way as https://github.com/kernelci/kernelci-backend/pull/141 
Both local and staging environment have been tested and proved to work.

**Comment by mgalka** [comment]
**Staging test cases**
1. Test group with test cases submitted to staging
_Request_
```
curl -X POST  https://staging-api.kernelci.org/test \
    -H 'Content-Type: application/json' \
    -H 'Authorization: AUTH_TOKEN' \
    -d @- <<'EOF'
     {
        "sub_groups": [],
        "board": "fake-board",
        "build_environment": "gcc-8",
        "git_commit": "42a5a774ef093e1ebbe4df290405900c7debe7af",
        "name": "Fake-test-group-with-test-cases-01",
        "metadata": {},
        "initrd_info": null,
        "git_branch": "mgalka",
        "version": "1.0",
        "mach": null,
        "board_instance": null,
        "job": "kernelci-local-snapshot-032",
        "file_server_resource": null,
        "initrd": null,
        "device_type": "fake-device-type",
        "arch": "x86_64",
        "kernel" : "kernelci-local-snapshot-032",
        "definition_uri": null,
        "defconfig": "x86_64_defconfig",
        "defconfig_full": "x86_64_defconfig",
        "image_type": null,
        "lab_name": "lab-mgalka",
        "index": 999,
        "job_id": null,
        "endian": null,
        "test_cases": [{"name": "FAKE_VIDIOC_QUERYCAP", 
                        "time": 1.0, 
                        "samples_sum": null,
                        "maximum": null,
                        "samples": null,
                        "attachments": [],
                        "minimum": null,
                        "vcs_commit": null,
                        "test_group_name": null,
                        "kvm_guest": null,
                        "version": "1.1",
                        "definition_uri": null,
                        "measurements": [],
                        "metadata": null,
                        "parameters": {},
                        "samples_sqr_sum": null,
                        "status": "PASS"}, 
                        {"name": "FAKE_MC-information-see-Media-Driver-Info-above",
                         "time": 1.0,
                         "samples_sum": null,
                         "maximum": null,
                         "samples": null,
                         "attachments": [],
                         "minimum": null,
                         "vcs_commit": null,
                         "test_group_name": null,
                         "kvm_guest": null,
                         "version": "1.1",
                         "definition_uri": null,
                         "measurements": [],
                         "metadata": null,
                         "parameters": {},
                         "samples_sqr_sum": null,
                         "status": "PASS"}, 
                         {"name": "USERPTR-select",
                          "time": 1.0,
                          "samples_sum": null,
                          "maximum": null,
                          "samples": null,
                          "attachments": [],
                          "minimum": null,
                          "vcs_commit": null,
                          "test_group_name": null,
                          "kvm_guest": null,
                          "version": "1.1", 
                          "definition_uri": null,
                          "measurements": [],
                          "metadata": null,
                          "parameters": {},
                          "samples_sqr_sum": null,
                          "status": "FAIL"}],
        "time": 1.0,
        "log": "Fake LOG\nJust some text\nNo parsing"
    } 
EOF
```

_Response_
```json
{"code":201,"reason":"Test group 'Fake-test-group-with-test-cases-01' created","result":[{"_id":{"$oid":"5d2c8374cf3a0f98e5fa534a"}}]}
```

2. Test group with missing mandatory fields submitted to staging

_Request_
```
curl -X POST  https://staging-api.kernelci.org/test \
    -H 'Content-Type: application/json' \
    -H 'Authorization: AUTH_TOKEN' \
    -d @- <<'EOF'
     {
        "sub_groups": [],
        "board": "fake-board",
        "git_commit": "42a5a774ef093e1ebbe4df290405900c7debe7af",
        "name": "Fake-test-group-with-test-cases-01",
        "metadata": {},
        "initrd_info": null,
        "git_branch": "mgalka",
        "version": "1.0",
        "mach": null,
        "board_instance": null,
        "job": "kernelci-local-snapshot-032",
        "file_server_resource": null,
        "initrd": null,
        "device_type": "fake-device-type",
        "kernel" : "kernelci-local-snapshot-032",
        "definition_uri": null,
        "defconfig": "x86_64_defconfig",
        "defconfig_full": "x86_64_defconfig",
        "image_type": null,
        "index": 999,
        "job_id": null,
        "endian": null,
        "test_cases": [{"name": "FAKE_VIDIOC_QUERYCAP", 
                        "time": 1.0, 
                        "samples_sum": null,
                        "maximum": null,
                        "samples": null,
                        "attachments": [],
                        "minimum": null,
                        "vcs_commit": null,
                        "test_group_name": null,
                        "kvm_guest": null,
                        "version": "1.1",
                        "definition_uri": null,
                        "measurements": [],
                        "metadata": null,
                        "parameters": {},
                        "samples_sqr_sum": null,
                        "status": "PASS"}, 
                        {"name": "FAKE_MC-information-see-Media-Driver-Info-above",
                         "time": 1.0,
                         "samples_sum": null,
                         "maximum": null,
                         "samples": null,
                         "attachments": [],
                         "minimum": null,
                         "vcs_commit": null,
                         "test_group_name": null,
                         "kvm_guest": null,
                         "version": "1.1",
                         "definition_uri": null,
                         "measurements": [],
                         "metadata": null,
                         "parameters": {},
                         "samples_sqr_sum": null,
                         "status": "PASS"}, 
                         {"name": "USERPTR-select",
                          "time": 1.0,
                          "samples_sum": null,
                          "maximum": null,
                          "samples": null,
                          "attachments": [],
                          "minimum": null,
                          "vcs_commit": null,
                          "test_group_name": null,
                          "kvm_guest": null,
                          "version": "1.1", 
                          "definition_uri": null,
                          "measurements": [],
                          "metadata": null,
                          "parameters": {},
                          "samples_sqr_sum": null,
                          "status": "FAIL"}],
        "time": 1.0,
        "log": "Fake LOG\nJust some text\nNo parsing"
    } 
EOF
```

_Response_
```json
{"code":400,"reason":"Provided JSON is not valid","errors":["One or more mandatory keys are missing: ['arch', 'build_environment', 'lab_name']"]}
```

**Comment by gctucker** [comment]
Thanks, testing this on staging today.

**Comment by gctucker** [comment]
Tested OK on staging, thanks!

**Pull request merged**
