### PR TITLE
T7884 Add handler for /bisect POST to save bisection results

### PR DESCRIPTION
**Pull request by gctucker**
Add a BisectHandler._post() method to handle POST requests and run a
task to update a BootBisectionDocument with the results.  This relies
on having a document previously created when triggering the bisection.

Signed-off-by: Guillaume Tucker <guillaume.tucker@collabora.com>

### CODE REVIEW

**Comment by MiloCasagrande** [comment]
Seems ok to me, do you want to test it on staging before?
We can merge and test the master branch directly before rolling out to kci.org.

**Comment by gctucker** [comment]
Thanks @MiloCasagrande, yes I want to test it first together with some changes in `lava-ci`.  Then there's another change to send bisection email reports, and once we've got all that I think it will be time to roll it out on production.

**Comment by gctucker** [comment]
I've tested it OK, just had to change `kernelci-celery.cfg` to allow POST requests on `/bisect`: https://github.com/kernelci/kernelci-backend-config/pull/20

**Comment by MiloCasagrande** [comment]
Sounds good. I'll merge it and then we can decide when to roll it out.

**Comment by gctucker** [comment]
Great, thanks.  I'm triggering another round of build/boot/bisect on staging with emails now, to verify it's all working as expected.  We'll probably need to do a final run again with the master branches on staging when it's all merged.

**Pull request merged**
