### PR TITLE
T6973 Enable boot bisection email report

### PR DESCRIPTION
**Pull request by gctucker**
Refactor email report handlers and add support for boot bisection reports.

Sample text output:
```
Bisection result for gtucker/kernelci-test (kernelci-test-063-7-g0cd604c06ee7) on bcm2837-rpi-3-b

  Good:       ce3c4d3ac34e HACK disable all{yes,no,mod}config and tinyconfig
  Bad:        0cd604c06ee7 NOISE Special cases aren't special enough...
  Found:      d4eaca92ba23 BREAK panic in initramfs

Checks:
  revert:     PASS
  verify:     PASS

Parameters:
  Tree:       gtucker
  URL:        https://gitlab.collabora.com/gtucker/linux.git
  Branch:     kernelci-test
  Target:     bcm2837-rpi-3-b
  Lab:        lab-mhart-dev
  Config:     defconfig
  Plan:       boot

Breaking commit found:

-------------------------------------------------------------------------------
commit d4eaca92ba238bd4b7d7bcab06618cd974480e2c
Author: Guillaume Tucker <guillaume.tucker@collabora.com>
Date:   Wed Aug 23 08:42:33 2017 +0100

    BREAK panic in initramfs

diff --git a/init/initramfs.c b/init/initramfs.c
index 02c08e35ad1a..c813ac723add 100644
--- a/init/initramfs.c
+++ b/init/initramfs.c
@@ -619,6 +619,9 @@ static int __init populate_rootfs(void)
 	printk(KERN_EMERG "Complex is better than complicated.\n");
 	printk(KERN_EMERG "Flat is better than nested.\n");
 #endif
+#if 1
+	panic("THIS MUST FAIL");
+#endif
 	/* If available load the bootloader supplied initrd */
 	if (initrd_start && !IS_ENABLED(CONFIG_INITRAMFS_FORCE)) {
 #ifdef CONFIG_BLK_DEV_RAM
-------------------------------------------------------------------------------


Git bisection log:

-------------------------------------------------------------------------------
git bisect start
# good: [ce3c4d3ac34e0c4aef6fbacc3d46c3531fbe6d1b] HACK disable all{yes,no,mod}config and tinyconfig
git bisect good ce3c4d3ac34e0c4aef6fbacc3d46c3531fbe6d1b
# bad: [0cd604c06ee759ed3e28b1158d31d48021e07579] NOISE Special cases aren't special enough...
git bisect bad 0cd604c06ee759ed3e28b1158d31d48021e07579
# good: [cfb9b35c526ed3a46becc1c661c7f35717034217] NOISE Flat is better than nested
git bisect good cfb9b35c526ed3a46becc1c661c7f35717034217
# bad: [91481bc5f3d3800f794dc0bc4d81299244e508bc] NOISE Sparse is better than dense
git bisect bad 91481bc5f3d3800f794dc0bc4d81299244e508bc
# bad: [d4eaca92ba238bd4b7d7bcab06618cd974480e2c] BREAK panic in initramfs
git bisect bad d4eaca92ba238bd4b7d7bcab06618cd974480e2c
# first bad commit: [d4eaca92ba238bd4b7d7bcab06618cd974480e2c] BREAK panic in initramfs
-------------------------------------------------------------------------------
```

### CODE REVIEW

**Comment by gctucker** [comment]
Testing this on staging now.

**Comment by gctucker** [comment]
Rebased this, doing one last round of tests.

@MiloCasagrande Does it look like this can be merged provided tests on staging are good?

**Comment by MiloCasagrande** [comment]
Yeah, it all looks good to me (took a while sorry, it's a rather big diff).

I'm only slightly concerned with the "parameters" fields alignment on the TXT email: with fixed-width fonts it's probably ok, but most webmail have variable-width fonts so those fields might be un-aligned.

It's something that can be easily fixed later though.

**Comment by gctucker** [comment]
Tested OK on staging, merging now.

**Pull request merged**
