### PR TITLE
lava_log_parser.py: add timestamps to HTML log output

### PR DESCRIPTION
**Pull request by gctucker**
Add timestamps from the LAVA log to the HTML parsed log output.

Signed-off-by: Guillaume Tucker <guillaume.tucker@collabora.com>

### CODE REVIEW

**Comment by gctucker** [comment]
Example output: https://people.collabora.com/~gtucker/tmp/boot-log-timestamps-2.html

**Comment by gctucker** [comment]
This might be easier to read: https://people.collabora.com/~gtucker/tmp/boot-log-timestamps-3.html

**Comment by mattface** [comment]
Does this do the same for the plain text output?

**Comment by mattface** [comment]
I vote for number 3 :)

**Comment by khilman** [comment]
I like timestamps-3 also.

**Comment by gctucker** [comment]
The text output is left unchanged and contains only the console output:
https://people.collabora.com/~gtucker/tmp/boot-log-timestamps-3.txt

The code currently in this PR generates the timestamps-3 version.

**Comment by gctucker** [comment]
Another example with a kernel panic:
https://people.collabora.com/~gtucker/tmp/boot-log-timestamps-3-panic.html

**Comment by gctucker** [comment]
New version with the start date/time at the top of the page:
https://people.collabora.com/~gtucker/tmp/boot-log-timestamps-4.html

**Comment by khilman** [comment]
Looks great!

**Pull request merged**
