### PR TITLE
Update unittest instructions per modern lore

### PR DESCRIPTION
**Pull request by danrue**
Signed-off-by: Dan Rue <dan.rue@linaro.org>

### CODE REVIEW

**Comment by danrue** [comment]
See issue #128 regarding the redis requirement.

**Comment by mattface** [comment]
LGTM

**Comment by gctucker** [comment]
Looks good but I got this error while running the sample instructions:
```
$ pip install -r ../requirements-dev.txt
[...]
ERROR: sphinxcontrib-httpdomain 1.7.0 has requirement Sphinx>=1.5, but you'll have sphinx 1.4.9 which is incompatible.
[...]
```

**Comment by gctucker** [comment]
The unit tests did pass though, in spite of the error message.  I guess that dependency isn't really one for what is covered in the unit tests, as they don't involve generating documentation with Sphinx.

**Comment by gctucker** [comment]
I've created this PR to remove the issue with Sphinx version: https://github.com/kernelci/kernelci-backend/pull/132

**Pull request merged**
