### PR TITLE
Remove a LOT of the email verboseness

### PR DESCRIPTION
**Pull request by mattface**
DO NOT MERGE

I've just put in this pull request so we can try my branch out on staging

### CODE REVIEW

**Comment by MiloCasagrande** [comment]
I manually applied this on staging.

**Comment by gctucker** [comment]
Do we still want to shorten the build and boot reports?

**Comment by khilman** [comment]
IMO, yes.  I think email reports should focus on red flags, like new regressions and failures, and summarize the rest, with links pointing to the frontend.

**Comment by mattface** [comment]
Yes I believe we do, though this review should be abandoned and reattempted properly

**Comment by gctucker** [comment]
@mattface How about closing this now as it's way behind, and maybe opening a new one in the light of recent discussions around verbosity of build reports?

**Pull request closed without merging**
