### PR TITLE
workflow: add main.yml with tests from Travis CI

### PR DESCRIPTION
**Pull request by mgalka**
Migrate tests run previously by Travis CI to GitHub actions.

Signed-off-by: Michal Galka <michal.galka@collabora.com>

### CODE REVIEW

**Comment by mgalka** [comment]
Changes tested on my fork of kernelci-backend. Work fine.

**Comment by gctucker** [comment]
Somehow the GitHub Action checks were not run for this PR.  Maybe something's missing with the YAML file?

**Comment by mgalka** [comment]
> Somehow the GitHub Action checks were not run for this PR. Maybe something's missing with the YAML file?

Isn't it that main.yml must be in the repository to get the checks?

**Comment by gctucker** [comment]
How strange, I've pushed a branch with the same name but in this repo rather than a fork, and created #272 with it, and now both PRs are running the checks...  I guess we'll be able to close #272 and merge this one if it works.

**Comment by gctucker** [comment]
OK the checks passed all fine.  I'll close #272 now, maybe that was just a GitHub glitch.

**Review by gctucker — CHANGES_REQUESTED** [review]
Actually `pip install -r requirements-dev.txt` works fine with `-r requirements.txt` inside it, see #273.  So please update this patch accordingly.

Also the commit subject should start with `workflows:` to be consistent.

**Review by gctucker — APPROVED** [review]

**Review by gctucker — APPROVED** [review]

**Pull request merged**
